### ISSUE TITLE
unable to get imge on frame buffer dispaly

### ISSUE THREAD

**Issue by divyashree123456** [zenhack/framebuffer-go#1]
Hi All,
I am trying to write a image to a frame buffer using "/github.com/zenhack/framebuffer-go" these packages ,i was not able to get a image on display .please suggest me any suggestions.

**Comment by zenhack** [comment]
What did you try, and how did it go wrong?

**Comment by divyashree123456** [comment]
Hi @zenhack 
I was trying to display a image on lvds display using frame buffer /dev/fb0 ,for that i was tried to use this packages i coludnt get any thing on image ,later i used  https://github.com/kaey/framebuffer ,and modified some functions and able to get image on display.
